spring.application.name=account-service
spring.profiles.active=stg
spring.cloud.config.profile=stg
server.port=9000
spring.config.import=optional:configserver:http://localhost:8888
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
logging.level.org.springframework=DEBUG

# Eureka Service Registry Configuration - Enable for microservices discovery
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.client.register-with-eureka=fa
#eureka.client.fetch-registry=true
#eureka.instance.prefer-ip-address=true

# Use 'dev' profile to enable these settings; keep 'stg' for staging as needed
spring.datasource.url=jdbc:h2:mem:testdb;IFEXISTS=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Expose the H2 console at /h2-console (disable in production)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


logging.file.name=logs/application.log


spring.jackson.datatype.datetime.write-dates-as-timestamps=false

#